version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app