name: Azure Container Apps Deploy
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - sprint-6-irene

jobs:
  build:
    name: Deploy Infra
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log GitHub Workspace
        run: echo $GITHUB_WORKSPACE
        
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: kreciperegistry
          containerAppName: krecipe-container-app
          resourceGroup: krecipe-resource-group
